In [62]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [63]:
pathAcceptedLoan = "../data/raw/accepted_2007_to_2018Q4.csv"
pathRejectedLoan = "../data/raw/rejected_2007_to_2018Q4.csv"

In [66]:
AcceptedLoan_df = pd.read_csv(pathAcceptedLoan, low_memory=False)

In [ ]:
AcceptedLoan_df = AcceptedLoan_df.apply(pd.to_numeric, errors='coerce')

column_drop = []
size = len(AcceptedLoan_df)
for col in AcceptedLoan_df.columns:
    null_ratio = AcceptedLoan_df[col].isnull().sum() / size * 100
    if null_ratio == 0:
        continue
    elif null_ratio >= 30:
        column_drop.append(col)
    else:
        if pd.api.types.is_object_dtype(AcceptedLoan_df[col]) or pd.api.types.is_categorical_dtype(AcceptedLoan_df[col]):
            mode_value = AcceptedLoan_df[col].mode()[0]
            if mode_value:
                AcceptedLoan_df[col] = AcceptedLoan_df[col].fillna(mode_value)
        else:
            if pd.api.types.is_numeric_dtype(AcceptedLoan_df[col]):
                median_value = AcceptedLoan_df[col].median()
                if not pd.isna(median_value):
                    AcceptedLoan_df[col] = AcceptedLoan_df[col].fillna(median_value)

print("Columns to drop:", column_drop)
AcceptedLoan_df.drop(columns=column_drop, inplace=True)
AcceptedLoan_df.shape

Columns to drop: ['member_id', 'term', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'mths_since_last_delinq', 'mths_since_last_record', 'initial_list_status', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'mths_since_last_major_derog', 'application_type', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'disbursement_method', 'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']

(2260701, 70)

In [69]:
AcceptedLoan_df.isnull().sum().sort_values(ascending=False).head(10)

id                 0
loan_amnt          0
funded_amnt        0
funded_amnt_inv    0
int_rate           0
installment        0
annual_inc         0
dti                0
delinq_2yrs        0
fico_range_low     0
dtype: int64

In [70]:
AcceptedLoan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 70 columns):
 #   Column                      Dtype
---  ------                      -----
 0   id                          float64
 1   loan_amnt                   float64
 2   funded_amnt                 float64
 3   funded_amnt_inv             float64
 4   int_rate                    float64
 5   installment                 float64
 6   annual_inc                  float64
 7   dti                         float64
 8   delinq_2yrs                 float64
 9   fico_range_low              float64
 10  fico_range_high             float64
 11  inq_last_6mths              float64
 12  open_acc                    float64
 13  pub_rec                     float64
 14  revol_bal                   float64
 15  revol_util                  float64
 16  total_acc                   float64
 17  out_prncp                   float64
 18  out_prncp_inv               float64
 19  total_pymnt                 float64
 20  total_pymnt_inv             float64
 21  total_rec_prncp             float64
 22  total_rec_int               float64
 23  total_rec_late_fee          float64
 24  recoveries                  float64
 25  collection_recovery_fee     float64
 26  last_pymnt_amnt             float64
 27  last_fico_range_high        float64
 28  last_fico_range_low         float64
 29  collections_12_mths_ex_med  float64
 30  policy_code                 float64
 31  acc_now_delinq              float64
 32  tot_coll_amt                float64
 33  tot_cur_bal                 float64
 34  total_rev_hi_lim            float64
 35  acc_open_past_24mths        float64
 36  avg_cur_bal                 float64
 37  bc_open_to_buy              float64
 38  bc_util                     float64
 39  chargeoff_within_12_mths    float64
 40  delinq_amnt                 float64
 41  mo_sin_old_il_acct          float64
 42  mo_sin_old_rev_tl_op        float64
 43  mo_sin_rcnt_rev_tl_op       float64
 44  mo_sin_rcnt_tl              float64
 45  mort_acc                    float64
 46  mths_since_recent_bc        float64
 47  mths_since_recent_inq       float64
 48  num_accts_ever_120_pd       float64
 49  num_actv_bc_tl              float64
 50  num_actv_rev_tl             float64
 51  num_bc_sats                 float64
 52  num_bc_tl                   float64
 53  num_il_tl                   float64
 54  num_op_rev_tl               float64
 55  num_rev_accts               float64
 56  num_rev_tl_bal_gt_0         float64
 57  num_sats                    float64
 58  num_tl_120dpd_2m            float64
 59  num_tl_30dpd                float64
 60  num_tl_90g_dpd_24m          float64
 61  num_tl_op_past_12m          float64
 62  pct_tl_nvr_dlq              float64
 63  percent_bc_gt_75            float64
 64  pub_rec_bankruptcies        float64
 65  tax_liens                   float64
 66  tot_hi_cred_lim             float64
 67  total_bal_ex_mort           float64
 68  total_bc_limit              float64
 69  total_il_high_credit_limit  float64
dtypes: float64(70)
memory usage: 1.2 GB

In [ ]:
size = len(AcceptedLoan_df)
for col in AcceptedLoan_df.columns:
    null_values = AcceptedLoan_df[col].isnull().sum()
    if null_values > 0.50 * size:
        print(col, ":", AcceptedLoan_df[col].nunique(), "dataTypes:", AcceptedLoan_df[col].dtype, "missingValues:", AcceptedLoan_df[col].isnull().sum(), "nan percentage: ", AcceptedLoan_df[col].isnull().sum() / len(AcceptedLoan_df) * 100, "%")

In [ ]:
for i in AcceptedLoan_df.columns:
    print(i, ":", AcceptedLoan_df[i].nunique(), "dataTypes:", AcceptedLoan_df[i].dtype, "missingValues:", AcceptedLoan_df[i].isnull().sum(), "nan percentage: ", AcceptedLoan_df[i].isnull().sum() / len(AcceptedLoan_df) * 100, "%")

loan_amnt : 1572 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
funded_amnt : 1572 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
funded_amnt_inv : 10057 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
term : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
int_rate : 673 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
installment : 93301 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
grade : 7 dataTypes: str missingValues: 0 nan percentage:  0.0 %
sub_grade : 35 dataTypes: str missingValues: 0 nan percentage:  0.0 %
emp_title : 512694 dataTypes: str missingValues: 0 nan percentage:  0.0 %
emp_length : 11 dataTypes: str missingValues: 0 nan percentage:  0.0 %
home_ownership : 6 dataTypes: str missingValues: 0 nan percentage:  0.0 %
annual_inc : 89368 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
verification_status : 3 dataTypes: str missingValues: 0 nan percentage:  0.0 %
issue_d : 139 dataTypes: str missingValues: 0 nan percentage:  0.0 %
loan_status : 9 dataTypes: str missingValues: 0 nan percentage:  0.0 %
pymnt_plan : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
purpose : 14 dataTypes: str missingValues: 0 nan percentage:  0.0 %
zip_code : 956 dataTypes: str missingValues: 0 nan percentage:  0.0 %
addr_state : 51 dataTypes: str missingValues: 0 nan percentage:  0.0 %
dti : 10845 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
delinq_2yrs : 37 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
earliest_cr_line : 754 dataTypes: str missingValues: 0 nan percentage:  0.0 %
fico_range_low : 48 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
fico_range_high : 48 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
inq_last_6mths : 28 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_acc : 91 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
pub_rec : 43 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
revol_bal : 102251 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
revol_util : 1430 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_acc : 152 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
initial_list_status : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
out_prncp : 356141 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
out_prncp_inv : 368481 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_pymnt : 1633864 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_pymnt_inv : 1311099 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_rec_prncp : 486463 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_rec_int : 635921 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_rec_late_fee : 18375 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
recoveries : 132777 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
collection_recovery_fee : 146222 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
last_pymnt_d : 136 dataTypes: str missingValues: 0 nan percentage:  0.0 %
last_pymnt_amnt : 704467 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
last_credit_pull_d : 141 dataTypes: str missingValues: 0 nan percentage:  0.0 %
last_fico_range_high : 72 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
last_fico_range_low : 71 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
collections_12_mths_ex_med : 16 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
policy_code : 1 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
application_type : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
acc_now_delinq : 9 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
tot_coll_amt : 15574 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
tot_cur_bal : 487688 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_acc_6m : 19 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_act_il : 54 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_il_12m : 19 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_il_24m : 31 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mths_since_rcnt_il : 405 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_bal_il : 162249 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
il_util : 280 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_rv_12m : 29 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
open_rv_24m : 50 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
max_bal_bc : 33726 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
all_util : 188 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_rev_hi_lim : 34220 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
inq_fi : 33 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_cu_tl : 62 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
inq_last_12m : 48 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
acc_open_past_24mths : 57 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
avg_cur_bal : 88597 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
bc_open_to_buy : 91500 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
bc_util : 1494 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
chargeoff_within_12_mths : 11 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
delinq_amnt : 2617 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mo_sin_old_il_acct : 566 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mo_sin_old_rev_tl_op : 787 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mo_sin_rcnt_rev_tl_op : 333 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mo_sin_rcnt_tl : 232 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mort_acc : 47 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mths_since_recent_bc : 546 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
mths_since_recent_inq : 26 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_accts_ever_120_pd : 44 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_actv_bc_tl : 42 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_actv_rev_tl : 57 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_bc_sats : 60 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_bc_tl : 76 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_il_tl : 122 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_op_rev_tl : 81 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_rev_accts : 117 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_rev_tl_bal_gt_0 : 50 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_sats : 91 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_tl_120dpd_2m : 7 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_tl_30dpd : 5 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_tl_90g_dpd_24m : 34 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
num_tl_op_past_12m : 33 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
pct_tl_nvr_dlq : 690 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
percent_bc_gt_75 : 284 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
pub_rec_bankruptcies : 12 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
tax_liens : 42 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
tot_hi_cred_lim : 529972 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_bal_ex_mort : 212777 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_bc_limit : 20309 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
total_il_high_credit_limit : 194137 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
hardship_flag : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
disbursement_method : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
debt_settlement_flag : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %

In [ ]:
AcceptedLoan_df['term'].unique()

<StringArray>
[' 36 months', ' 60 months']
Length: 2, dtype: str

In [ ]:
AcceptedLoan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 104 entries, loan_amnt to debt_settlement_flag
dtypes: float64(83), str(21)
memory usage: 1.8 GB

In [ ]:
AcceptedLoan_df.shape

(2260701, 104)

In [ ]:
AcceptedLoan_df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,...,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,...,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,...,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,...,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,N,Cash,N
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,...,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N

In [ ]:
AcceptedLoan_df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,...,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06
mean,1.504686e+04,1.504159e+04,1.502336e+04,1.309281e+01,4.458047e+02,7.799213e+04,1.880967e+01,3.068707e-01,6.985876e+02,7.025878e+02,...,8.035826e-02,2.043268e+00,9.429802e+01,4.101958e+01,1.281142e-01,4.676824e-02,1.730881e+05,4.989304e+04,2.268014e+04,4.237192e+04
std,9.190199e+03,9.188366e+03,9.192285e+03,4.832105e+00,2.671722e+02,1.126953e+05,1.418749e+01,8.672199e-01,3.301046e+01,3.301133e+01,...,4.860507e-01,1.811686e+00,8.952810e+00,3.641322e+01,3.645142e-01,3.775225e-01,1.810299e+05,4.992334e+04,2.300499e+04,4.501134e+04
min,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,6.140000e+02,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.188000e+01,0.000000e+00,6.750000e+02,6.790000e+02,...,0.000000e+00,1.000000e+00,9.170000e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.697600e+04,1.979600e+04,7.800000e+03,1.309400e+04
50%,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.783000e+01,0.000000e+00,6.900000e+02,6.940000e+02,...,0.000000e+00,2.000000e+00,1.000000e+02,3.330000e+01,0.000000e+00,0.000000e+00,1.075710e+05,3.700100e+04,1.589000e+04,3.144600e+04
75%,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.448000e+01,0.000000e+00,7.150000e+02,7.190000e+02,...,0.000000e+00,3.000000e+00,1.000000e+02,6.670000e+01,0.000000e+00,0.000000e+00,2.521970e+05,6.347100e+04,2.990000e+04,5.760100e+04
max,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,8.500000e+02,...,5.800000e+01,3.200000e+01,1.000000e+02,1.000000e+02,1.200000e+01,8.500000e+01,9.999999e+06,3.408095e+06,1.569000e+06,2.118996e+06