In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
pathAcceptedLoan = "../data/raw/accepted_2007_to_2018Q4.csv"
pathRejectedLoan = "../data/raw/rejected_2007_to_2018Q4.csv"

In [3]:
AcceptedLoan_df = pd.read_csv(pathAcceptedLoan, low_memory=False)

In [4]:
AcceptedLoan_df.drop(columns=['id', 'member_id', 'url', 'desc', 'title'], inplace=True)

In [5]:

for col in AcceptedLoan_df.columns:
    null_values = AcceptedLoan_df[col].isnull().sum()
    if null_values > 0 and null_values < 1000:
        AcceptedLoan_df[col] = AcceptedLoan_df[col].fillna(AcceptedLoan_df[col].mode()[0])

In [12]:
for i in AcceptedLoan_df.columns[0:10]:
    print(i, ":", AcceptedLoan_df[i].nunique(), "dataTypes:", AcceptedLoan_df[i].dtype, "missingValues:", AcceptedLoan_df[i].isnull().sum(), "nan percentage: ", AcceptedLoan_df[i].isnull().sum() / len(AcceptedLoan_df) * 100, "%")

loan_amnt : 1572 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
funded_amnt : 1572 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
funded_amnt_inv : 10057 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
term : 2 dataTypes: str missingValues: 0 nan percentage:  0.0 %
int_rate : 673 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
installment : 93301 dataTypes: float64 missingValues: 0 nan percentage:  0.0 %
grade : 7 dataTypes: str missingValues: 0 nan percentage:  0.0 %
sub_grade : 35 dataTypes: str missingValues: 0 nan percentage:  0.0 %
emp_title : 512694 dataTypes: str missingValues: 167002 nan percentage:  7.387177693998455 %
emp_length : 11 dataTypes: str missingValues: 146940 nan percentage:  6.499753837415917 %

In [7]:
AcceptedLoan_df['term'].unique()

<StringArray>
[' 36 months', ' 60 months']
Length: 2, dtype: str

In [8]:
AcceptedLoan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 146 entries, loan_amnt to settlement_term
dtypes: float64(112), str(34)
memory usage: 2.5 GB

In [9]:
AcceptedLoan_df.shape

(2260701, 146)

In [10]:
AcceptedLoan_df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
AcceptedLoan_df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.258957e+06,2.260701e+06,2.260701e+06,2.260701e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,1.504686e+04,1.504159e+04,1.502336e+04,1.309281e+01,4.458047e+02,7.799213e+04,1.882420e+01,3.068707e-01,6.985876e+02,7.025878e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,9.190199e+03,9.188366e+03,9.192285e+03,4.832105e+00,2.671722e+02,1.126953e+05,1.418333e+01,8.672199e-01,3.301046e+01,3.301133e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,6.140000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,6.790000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,6.940000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,7.190000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,8.500000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000